### find user by email
GET {{url}}/users/ricardo@teste.com
Accept: application/json

### create a new user
POST {{url}}/users
Content-Type: application/json

{
  "name": "zika Santos",
  "email": "ricardo@teste.com2",
  "password": "q1w2e3r4!",
  "admin": false
}

### create a new tag
POST {{url}}/tags
Content-Type: application/json

{
  "name": "tag1"
}

### Authenticate user
POST {{url}}/login
Content-Type: application/json

{
  "email": "ricardo@teste.com2",
  "password": "q1w2e3r4!"
}