### find user by email
GET {{url}}/users
Accept: application/json
Authorization: Bearer {{auth_admin_token}}

### create a new user
POST {{url}}/users
Content-Type: application/json

{
  "name": "user admin",
  "email": "admin@admin.com",
  "password": "q1w2e3r4!",
  "admin": true
}

### create a new tag
POST {{url}}/tags
Content-Type: application/json
Authorization: Bearer {{auth_admin_token}}

{
  "name": "GOD"
}

### Authenticate user
POST {{url}}/login
Content-Type: application/json

{
  "email": "ricardo@santos.com",
  "password": "q1w2e3r4!"
}

### Create compliment
POST {{url}}/compliments
Content-Type: application/json
Authorization: Bearer {{auth_token_2}}

{
  "tag_id": "d89a5a13-7378-4e60-829c-f9511cbe9543",
  "user_receiver": "233ff1fb-9225-4d4e-8123-f952806fd671",
  "message": "Obrigado por me ajudar a alcançar o objetivo"
}

### list user received compliments
GET {{url}}/users/compliments/send
Accept: application/json
Authorization: Bearer {{auth_token_2}}


### list user sent compliments
GET {{url}}/users/compliments/receive
Accept: application/json
Authorization: Bearer {{auth_admin_token}}


### list all tags
GET {{url}}/tags
Accept: application/json
Authorization: Bearer {{auth_admin_token}}



