### find user by email
GET {{url}}/users/ricardo@teste.com3
Accept: application/json

### create a new user
POST {{url}}/users
Content-Type: application/json

{
  "name": "user admin",
  "email": "admin@admin.com",
  "password": "q1w2e3r4!",
  "admin": true
}

### create a new tag
POST {{url}}/tags
Content-Type: application/json
Authorization: Bearer {{auth_admin_token}}

{
  "name": "GOD"
}

### Authenticate user
POST {{url}}/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "q1w2e3r4!"
}

### Create compliment
POST {{url}}/compliments
Content-Type: application/json

{
  "tag_id": "d89a5a13-7378-4e60-829c-f9511cbe9543",
  "user_sender": "ea79f4b0-3eb6-4280-9b3d-246e6e412c0e",
  "user_receiver": "03975c3d-0a86-4c75-9f07-1b53872cab76",
  "message": "Teste de mensagem"
}

